version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: yutagame-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: yutagame
      MYSQL_USER: yuta_user
      MYSQL_PASSWORD: yuta_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
