// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/admins": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "条件に従いAdminユーザー情報の一覧を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admins"
                ],
                "summary": "Adminユーザー一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ページ番号 (指定するとページングモード)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "表示件数 (10, 30, 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "自由入力のテキスト検索（Adminユーザー名）",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "page指定時",
                        "schema": {
                            "$ref": "#/definitions/handler.PaginatedResponse-model_Admin"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しいAdminユーザーフアカウントを作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admins"
                ],
                "summary": "Adminユーザー新規登録",
                "parameters": [
                    {
                        "description": "Adminユーザー登録情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.AdminSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Admin"
                        }
                    },
                    "400": {
                        "description": "バリデーション・重複エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/admins/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのAdminユーザー情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admins"
                ],
                "summary": "Adminユーザー詳細取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AdminユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Admin"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのAdminユーザーの名前、メール、パスワード、権限を更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admins"
                ],
                "summary": "Adminユーザー情報更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AdminユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Adminユーザー更新情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.AdminSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Admin"
                        }
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのAdminユーザーアカウントを削除します。",
                "tags": [
                    "Admins"
                ],
                "summary": "Adminユーザー削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AdminユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/games": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "条件に従いゲーム情報の一覧を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "ゲーム一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ページ番号 (指定するとページングモード)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "表示件数 (10, 30, 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "自由入力のテキスト検索（ゲーム名）",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "メーカーIDの複数指定",
                        "name": "manufacturerIDs",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "機種IDの複数指定",
                        "name": "machineIDs",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "ジャンルIDの複数指定",
                        "name": "genreIDs",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "キーワードIDの複数指定",
                        "name": "keywordIDs",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "page指定時",
                        "schema": {
                            "$ref": "#/definitions/handler.PaginatedResponse-model_Game"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しいゲームの情報をデータベースに登録します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "ゲーム新規登録",
                "parameters": [
                    {
                        "description": "ゲーム登録情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.GameSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Game"
                        }
                    }
                }
            }
        },
        "/admin/games/code/{code}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたコードのゲーム詳細情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "ゲーム詳細取得（コード指定）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ゲームコード",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Game"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/games/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDまたはコードのゲーム詳細情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "ゲーム詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ゲームIDまたはゲームコード",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Game"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのゲーム情報更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "ゲーム情報更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ゲームID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ゲーム更新情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.GameSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Game"
                        }
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのゲーム情報を削除します。",
                "tags": [
                    "Games"
                ],
                "summary": "ゲーム情報削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ゲームID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/genres": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Genres"
                ],
                "summary": "ジャンル一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ページ番号 (指定するとページングモード)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "表示件数 (10, 30, 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "検索キーワード (名前またはカナの部分一致)",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "page指定時",
                        "schema": {
                            "$ref": "#/definitions/handler.PaginatedResponse-model_Genre"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しいジャンルを作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Genres"
                ],
                "summary": "ジャンル新規登録",
                "parameters": [
                    {
                        "description": "ジャンル登録情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.GenreSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Genre"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/genres/code/{code}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたコードのジャンル情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Genres"
                ],
                "summary": "ジャンル詳細取得（コード指定）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ジャンルコード",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Genre"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/genres/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDまたはコードのジャンル情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Genres"
                ],
                "summary": "ジャンル詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ジャンルIDまたはジャンルコード",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Genre"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのジャンルの情報を更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Genres"
                ],
                "summary": "ジャンル情報更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ジャンルID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ジャンル更新情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.GenreSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Genre"
                        }
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのジャンルを削除します。",
                "tags": [
                    "Genres"
                ],
                "summary": "ジャンル削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ジャンルID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/keyword/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのキーワードの情報を更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keywords"
                ],
                "summary": "キーワード情報更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "キーワードID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "キーワード更新情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.KeywordSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Keyword"
                        }
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/keywords": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keywords"
                ],
                "summary": "キーワード一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ページ番号 (指定するとページングモード)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "表示件数 (10, 30, 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "検索キーワード (名前またはカナの部分一致)",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "page指定時",
                        "schema": {
                            "$ref": "#/definitions/handler.PaginatedResponse-model_Keyword"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しいキーワードを作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keywords"
                ],
                "summary": "キーワード新規登録",
                "parameters": [
                    {
                        "description": "キーワード登録情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.KeywordSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Keyword"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/keywords/code/{code}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたコードのキーワード情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keywords"
                ],
                "summary": "キーワード詳細取得（コード指定）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "キーワードコード",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Keyword"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/keywords/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDまたはコードのキーワード情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keywords"
                ],
                "summary": "キーワード詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "キーワードIDまたはキーワードコード",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Keyword"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのキーワードを削除します。",
                "tags": [
                    "Keywords"
                ],
                "summary": "キーワード削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "キーワードID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "description": "メールアドレスとパスワードでログインし、JWTトークンを発行します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Adminユーザーログイン",
                "parameters": [
                    {
                        "description": "ログイン情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "tokenが返ります",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/machines": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登録されているすべてのハードウェア（機種）マスタを取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Machines"
                ],
                "summary": "機種一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ページ番号 (指定するとページングモード)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "表示件数 (10, 30, 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "自由入力のテキスト検索（ゲーム名）",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "メーカーIDの複数指定",
                        "name": "manufacturerIDs",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "page指定時",
                        "schema": {
                            "$ref": "#/definitions/handler.PaginatedResponse-model_Machine"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しい機種情報をデータベースに登録します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Machines"
                ],
                "summary": "機種新規登録",
                "parameters": [
                    {
                        "description": "機種登録情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.MachineSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Machine"
                        }
                    }
                }
            }
        },
        "/admin/machines/code/{code}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたコードの機種情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Machines"
                ],
                "summary": "機種詳細取得（コード指定）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "機種コード",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Machine"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/machines/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDまたはコードの機種情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Machines"
                ],
                "summary": "機種詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "機種IDまたは機種コード",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Machine"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDの機種情報更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Machines"
                ],
                "summary": "機種情報更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "機種ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ゲーム更新情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.MachineSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Machine"
                        }
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDの機種情報を削除します。",
                "tags": [
                    "Machines"
                ],
                "summary": "機種情報削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "機種ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/manufacturers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufacturers"
                ],
                "summary": "メーカー一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ページ番号 (指定するとページングモード)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "表示件数 (10, 30, 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "検索キーワード (名前またはカナの部分一致)",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "page指定時",
                        "schema": {
                            "$ref": "#/definitions/handler.PaginatedResponse-model_Manufacturer"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しいメーカーを作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufacturers"
                ],
                "summary": "メーカー新規登録",
                "parameters": [
                    {
                        "description": "メーカー情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.ManufacturerSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Manufacturer"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/manufacturers/code/{code}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたコードのメーカー情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufacturers"
                ],
                "summary": "メーカー詳細取得（コード指定）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "メーカーコード",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Manufacturer"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/manufacturers/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDまたはコードのメーカー情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufacturers"
                ],
                "summary": "メーカー詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "メーカーIDまたはメーカーコード",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Manufacturer"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのメーカーの情報を更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufacturers"
                ],
                "summary": "メーカー情報更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "メーカーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "メーカー更新情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.ManufacturerSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Genre"
                        }
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのメーカーを削除します。",
                "tags": [
                    "Manufacturers"
                ],
                "summary": "メーカー削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ジメーカID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "条件に従いユーザー情報の一覧を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "ユーザー一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ページ番号 (指定するとページングモード)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "表示件数 (10, 30, 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "自由入力のテキスト検索（Adminユーザー名）",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "page指定時",
                        "schema": {
                            "$ref": "#/definitions/handler.PaginatedResponse-model_User"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しいユーザーアカウントを作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "ユーザー新規登録",
                "parameters": [
                    {
                        "description": "ユーザー登録情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.UserSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "バリデーション・重複エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのユーザー情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "ユーザー詳細取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "404": {
                        "description": "未検出エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのAdminユーザーの名前、メール、パスワードを更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "ユーザー情報更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ユーザー更新情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.UserSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのユーザー情報を削除します。",
                "tags": [
                    "Users"
                ],
                "summary": "ユーザー削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AdminユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "エラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.AdminSaveRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "description": "更新処理時、空文字の場合は「変更なし」として取り扱われます",
                    "type": "string"
                },
                "roleType": {
                    "type": "string"
                }
            }
        },
        "admin.GameSaveRequest": {
            "type": "object",
            "properties": {
                "catchCopy": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "genreId": {
                    "type": "integer"
                },
                "isClear": {
                    "type": "boolean"
                },
                "isFavourite": {
                    "type": "boolean"
                },
                "isPlay": {
                    "type": "boolean"
                },
                "kana": {
                    "type": "string"
                },
                "keywordIds": {
                    "description": "💡 紐付けるキーワードのID配列",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "listPrice": {
                    "type": "integer"
                },
                "machineId": {
                    "type": "integer"
                },
                "manufacturerId": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "officialSiteUrl": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "releaseDate": {
                    "description": "フロントからは文字列(\"YYYY-MM-DD\")で受け取る",
                    "type": "string"
                },
                "subCatch": {
                    "type": "string"
                },
                "subGenre": {
                    "type": "string"
                },
                "youtubeUrl": {
                    "type": "string"
                }
            }
        },
        "admin.GenreSaveRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "kana": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                }
            }
        },
        "admin.KeywordSaveRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "kana": {
                    "type": "string"
                },
                "keywordType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                }
            }
        },
        "admin.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "admin.MachineSaveRequest": {
            "type": "object",
            "properties": {
                "abbreviation": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "kana": {
                    "type": "string"
                },
                "machineType": {
                    "type": "string"
                },
                "manufacturerId": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "releaseDate": {
                    "description": "フロントからは文字列(\"YYYY-MM-DD\")で受け取る",
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                }
            }
        },
        "admin.ManufacturerSaveRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "kana": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                }
            }
        },
        "admin.UserSaveRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "description": "更新処理時、空文字の場合は「変更なし」として取り扱われます",
                    "type": "string"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.PaginatedResponse-model_Admin": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "admins や items などのキー名に依存しないよう、汎用的に \"data\" とします",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Admin"
                    }
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "handler.PaginatedResponse-model_Game": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "admins や items などのキー名に依存しないよう、汎用的に \"data\" とします",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Game"
                    }
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "handler.PaginatedResponse-model_Genre": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "admins や items などのキー名に依存しないよう、汎用的に \"data\" とします",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Genre"
                    }
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "handler.PaginatedResponse-model_Keyword": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "admins や items などのキー名に依存しないよう、汎用的に \"data\" とします",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Keyword"
                    }
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "handler.PaginatedResponse-model_Machine": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "admins や items などのキー名に依存しないよう、汎用的に \"data\" とします",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Machine"
                    }
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "handler.PaginatedResponse-model_Manufacturer": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "admins や items などのキー名に依存しないよう、汎用的に \"data\" とします",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Manufacturer"
                    }
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "handler.PaginatedResponse-model_User": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "admins や items などのキー名に依存しないよう、汎用的に \"data\" とします",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.User"
                    }
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "model.Admin": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "roleType": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Game": {
            "type": "object",
            "properties": {
                "catchCopy": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "genre": {
                    "$ref": "#/definitions/model.Genre"
                },
                "genreId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "imageKey": {
                    "type": "string"
                },
                "isClear": {
                    "type": "boolean"
                },
                "isFavourite": {
                    "type": "boolean"
                },
                "isPlay": {
                    "type": "boolean"
                },
                "kana": {
                    "type": "string"
                },
                "keywords": {
                    "description": "💡 凄まじいポイント：GORMに「game_keywordsという中間テーブルを使って、紐づくKeywordsを全自動でガッチャンコしてね」と1行で命令します",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Keyword"
                    }
                },
                "listPrice": {
                    "type": "integer"
                },
                "machine": {
                    "$ref": "#/definitions/model.Machine"
                },
                "machineId": {
                    "type": "integer"
                },
                "manufacturer": {
                    "description": "💡 依存関係の解消：GORMの1対多（Belongs To）リレーション群",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Manufacturer"
                        }
                    ]
                },
                "manufacturerId": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "officialSiteUrl": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "releaseDate": {
                    "type": "string"
                },
                "subCatch": {
                    "type": "string"
                },
                "subGenre": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "youtubeUrl": {
                    "type": "string"
                }
            }
        },
        "model.Genre": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageKey": {
                    "type": "string"
                },
                "kana": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Keyword": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kana": {
                    "type": "string"
                },
                "keywordType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Machine": {
            "type": "object",
            "properties": {
                "abbreviation": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageKey": {
                    "type": "string"
                },
                "kana": {
                    "type": "string"
                },
                "machineType": {
                    "type": "string"
                },
                "manufacturer": {
                    "description": "💡 依存関係の解消：GORMに「メーカー情報も連動してね」と教えるリレーション定義",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Manufacturer"
                        }
                    ]
                },
                "manufacturerId": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "releaseDate": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Manufacturer": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageKey": {
                    "type": "string"
                },
                "kana": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Bearer {token}\" の形式でJWTトークンを入力してください。",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Yutagame Backend API",
	Description:      "所持ゲーム管理システムのバックエンドAPI仕様書",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
